---
abstract: 'SOAP Web Service Addressing'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Compile-C14N
no_index:
  directory:
    - t
    - inc
requires:
  Log::Report: 0.991
  Scalar::Util: 0
  Test::More: 0.98
  XML::Compile: 1.30
  XML::Compile::Cache: 0.995
  XML::LibXML: 1.94
version: 0.93
