--- #YAML:1.0
name:               XML-Compile-C14N
version:            0.10
abstract:           SOAP Web Service Addressing
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       0
    File::Spec:           0
    Log::Report:          0.92
    Test::More:           0.54
    XML::Compile:         1.21
    XML::Compile::Cache:  0.98
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
